main.py
import config
import os

from core.redis   import rds

from version import VERSION
from flask   import Flask
from datetime import datetime

# Import Blueprints
from views.view_index      import index
from views.view_login      import login
from views.view_logout     import logout
from views.view_notes      import notes


app = Flask(__name__)

# Initialize Blueprints
app.register_blueprint(index)
app.register_blueprint(login)
app.register_blueprint(logout)
app.register_blueprint(notes)

app.config.update(
  SESSION_COOKIE_SAMESITE='Strict',
)
app.secret_key = os.urandom(24)

# Set Security Headers
@app.after_request
def add_security_headers(resp):
  if config.WEB_SECURITY:
    resp.headers['Content-Security-Policy'] = config.WEB_SEC_HEADERS['CSP']
    resp.headers['X-Content-Type-Options'] = config.WEB_SEC_HEADERS['CTO']
    resp.headers['X-XSS-Protection'] = config.WEB_SEC_HEADERS['XSS']
    resp.headers['X-Frame-Options'] = config.WEB_SEC_HEADERS['XFO']
    resp.headers['Referrer-Policy'] = config.WEB_SEC_HEADERS['RP']
    resp.headers['Server'] = config.WEB_SEC_HEADERS['Server']
  return resp  


@app.context_processor
def show_version():
  return dict(version=VERSION)

if __name__ == '__main__':  
  app.run(debug = True, 
          host  = config.WEB_HOST, 
          port  = config.WEB_PORT,
          threaded=True,
          use_evalex=False)

views/view_index.py
from core.security import session_required
from flask import (
  Blueprint, 
  request, 
  redirect,
  make_response,
  render_template
)

index = Blueprint('index', __name__,
                   template_folder='templates')

@index.route('/')
@session_required
def view_index():
  return redirect('/notes')

views/view_login.py
from core.utils import Utils
from core.redis import rds
from core.security import verify_password

from flask import (
  Blueprint, 
  render_template, 
  request,
  session,
  redirect
)

login = Blueprint('login', __name__,
                  template_folder='templates')

@login.route('/login', methods=['GET', 'POST'])
def view_login():
  utils = Utils()
  msg = ''
  
  if request.method == 'POST':
    username = request.form.get('username', None)
    password = request.form.get('password', None)
    
    if rds.is_ip_blocked(request.remote_addr):
      return render_template('login.html', err='Your IP has been blocked.')
    
    if verify_password(username, password):
      session['session'] = username
      return redirect('/')
    else:
      return render_template('login.html', err='Incorrect username or password. \
                                                After 5 attempts, you will get blocked.')
  
  if not utils.is_version_latest():
    msg = 'New Version is Available'
  
  return render_template('login.html', msg=msg)

views/view_logout.py
from core.security import session_required
from flask import (
  Blueprint,   
  redirect,
  flash,
  session
)

logout = Blueprint('logout', __name__,
                    template_folder='templates')

@logout.route('/logout')
@session_required
def view_logout():
  if session.get('session'):
    session.pop('session')

  flash('Logged out successfully', 'success')

  return redirect('/login')

views/view_notes.py
from flask import Blueprint, render_template, request, url_for, redirect, flash
from core.redis import rds
from core.security import session_required


notes = Blueprint('notes', __name__,
                    template_folder='templates')


@notes.route('/notes')
@session_required
def view_notes():
    my_param_note = request.args.get('id')
    my_main_note = None

    # Searchs
    my_notes = my_param_note
    
        # Nothing found
    my_notes = rds.get_json('notes')
    if not my_param_note and my_notes:
        # Show first result
        my_main_note = my_notes[0]
    else:
    # Show first note
        try:
            my_note_temp = rds.get_json('notes')
            for note in my_note_temp:
                if note['title'] == my_param_note:
                    my_main_note = note
                    break
            # Is there any note in the database?
        except:
            flash('No such note was written','error')
        
    # Data for template
    data = dict()
    data['notes'] = my_notes
    data['main_note'] = my_main_note

    return render_template('items/dashboard.html', data=data)

@notes.route('/newnote')
@session_required
def new():
    return render_template('items/new.html')


@notes.route('/newnote/save', methods=['POST'])
@session_required
def save_note():
    myNote = {'title':request.form['title'].strip(),'text': request.form['text'].strip()}
    # Create
    tmp = rds.get_json('notes')
    if tmp:
        tmp.insert(0,myNote)
    else:
        tmp = [myNote]
    rds.store_json('notes',tmp)
    return redirect(url_for('notes.view_notes'))


@notes.route('/editnote')
@session_required
def edit(data=None):
    my_main_note = None
    id = request.args.get('id')
    my_note_temp = rds.get_json('notes')
    for note in my_note_temp:
        if note['title'] == id:
            my_main_note = note
            break

    data= {}
    data['main_note'] = my_main_note
    return render_template('items/edit.html', data=data)


@notes.route('/edit_note', methods=['POST'])
@session_required
def edit_note(data=None):
    if request.form['id']:
        # Update
        my_notes = rds.get_json('notes')
        for i in range(0,len(my_notes)):
            if my_notes[i]['title'] == request.form['id']:
                my_notes[i] = {'title':request.form['title'].strip(),'text': request.form['text'].strip()}
                break

        #my_note.title = request.form['title']
        #my_note.text = request.form['text']
        rds.store_json('notes',my_notes)

    return redirect(url_for('notes.view_notes'))


@notes.route('/deletenote')
@session_required
def delete():
    id = request.args.get('id')
    tmp = rds.get_json('notes')
    my_note = {}
    for i in tmp:
        if i['title'] == id:
            my_note = i 
            break
    data = dict()
    data['main_note'] = my_note

    return render_template('items/delete.html', data=data)


@notes.route('/delete_note')
@session_required
def delete_note():
    id = request.args.get('id')
    # Delete
    tmp = rds.get_json('notes')
    for i in range(0,len(tmp)):
        print(i)
        if tmp[i]['title'] == id:
            del tmp[i] 
            break
    if tmp:
        rds.store_json('notes',tmp)
    else:
        rds.delete('notes')

    return redirect(url_for('notes.view_notes', id=id))

templates/items/dashboard.html
{% extends 'layouts/master.html' %}
{% block contain %}
<div class="row">
  <div class="col-sm-12 text-right">
    <strong>{{username}}</strong>
    <a href="{{ url_for('logout.view_logout') }}" class="btn btn-primary">Logout</a>
  </div>
</div>
<br/>
<div class="row">
  <div class="col-md-6">
    <a href="/newnote" class="btn btn-success">New</a>
  </div>
  <div class="col-md-6 text-right">
    {%- if data.main_note -%}
    <a href="/editnote?id={{data['main_note']['title']}}" class="btn btn-warning">Edit</a>
    <a href="/deletenote?id={{data['main_note']['title']}}" class="btn btn-danger">Delete</a>
    {% endif %}
  </div>
</div>
<br/>
<div class="row">
  
  <div class="col-md-4">
    
    <div class="list-group">
      
       {% if data.notes %}

        <div class="input-group">
          <input name="q" type="text"  id="searchInput" onkeyup="searchFunction()" class="form-control" style="background: transparent;color: white;border: 2px solid rgba(255, 255, 255, .25); width: 70%;" placeholder="Search for...">
          <span class="input-group-btn">
          </span>
        </div>
      <ul id="notesUL">
      {% for note in data.notes %}
      <li> <a href="/notes?id={{note['title']}}" class="list-group-item">
        <h4 class="list-group-item-heading" style="color: #444;">{{note['title']}}</h4>
        <p class="list-group-item-text" style="color: black;">
          {% if note['text']|length > 140 %}
          {{ note['text'][:140] + '...' }}
          {% else %}
          {{ note['text']|safe }}
          {% endif %}
        </p>
      </a></li>
      {% endfor %}
    </ul>
      {% else %}
      <h4 class="list-group-item-heading">No Notes</h4>
      {% endif %}
    </div>

  </div>
  <div class="col-md-8">
    {%- if data.main_note -%}
    <div class="panel panel-default">
      <div class="panel-body">
        <h3>
          {{ data.main_note['title'] }}
        </h3>
        {{ data.main_note['text'] }}
      </div>
    </div>
    {% endif %}
  </div>
</div>
<script>
  function searchFunction() {
      var input, filter, ul, li, a, i, txtValue;
      input = document.getElementById("searchInput");
      filter = input.value.toUpperCase();
      ul = document.getElementById("notesUL");
      li = ul.getElementsByTagName("li");
      for (i = 0; i < li.length; i++) {
          a = li[i].getElementsByTagName("a")[0];
          txtValue = a.textContent || a.innerText;
          if (txtValue.toUpperCase().indexOf(filter) > -1) {
              li[i].style.display = "";
          } else {
              li[i].style.display = "none";
          }
      }
  }
  </script>
{% endblock %}

templates/items/delete.html
{% extends 'layouts/master.html' %}
{% block contain %}
<div class="row">
  <div class="col-sm-6"><h4>Do you want to delete this note?</h4></div>
  <div class="col-sm-6 text-right">
    <a href="/notes" class="btn btn-danger">No, please!</a>
    <a href="/delete_note?id={{data['main_note']['title']}}" class="btn btn-success">Yes</a>
  </div>
</div>
<br/>
<div class="row">
  <div class="panel panel-default">
      <div class="panel-body">
        <h3>
          {{ data['main_note']['title']}}
        </h3>
        {{ data['main_note']['text'] }}
      </div>
    </div>
</div>
{% endblock %}

templates/items/edit.html
{% extends 'layouts/master.html' %}
{% block contain %}
<form action="/edit_note" method="post">
  <input name="id" type="hidden" value="{{ data['main_note']['title'] }}"/>
  <div class="row">
    <div class="col-xs-6">
      <a href="/notes" class="btn btn-danger">Back</a>
    </div>
    <div class="col-xs-6 text-right">
      <button type="submit" class="btn btn-success">Edit</button>
    </div>
  </div>
  <br/>
  <div class="row">
    <input type="text" name="title" class="form-control" required value="{{ data['main_note']['title'] }}">
    <textarea name="text" class="form-control" rows="10" required>{{ data['main_note']['text'] }}</textarea>
  </div>
</form>
{% endblock %}

templates/items/new.html
{% extends 'layouts/master.html' %}
{% block contain %}

<form action="/newnote/save" method="post">
  <div class="row">
    <div class="col-xs-6">
      <a href="/notes" class="btn btn-danger">Back</a>
    </div>
    <div class="col-xs-6 text-right">
      <button type="submit" class="btn btn-success">Save</button>
    </div>
  </div>
  <br/>
  <div class="row">
    <input type="text" name="title" class="form-control" placeholder="Title..." required>
    <textarea name="text" class="form-control" rows="10" placeholder="Your text..." required></textarea>
  </div>
</form>
{% endblock %}

templates/layouts/master.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8"/>
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0"/>
    <link href={{url_for('static',filename="vendor/flatly/bootstrap.css")}} rel="stylesheet">
    <title>Flask Notes</title>
  </head>
  <body>
    <div class="container">
      <div class="page-header">
        <h1 class="text-center">
          <small>Flask Notes</small>
        </h1>
      </div>
      <div class="row">
        {% block contain %}
        {% endblock %}
      </div>
    </div>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-46470654-2', 'auto');
  ga('send', 'pageview');

</script>
  </body>
</html>

templates/login.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Flask Notes</title>
    <link href={{ url_for('static', filename="vendor/bootstrap4/css/bootstrap.min.css") }}  rel="stylesheet">
    <link href={{ url_for('static', filename="css/auth.css") }}  rel="stylesheet">
    <link href={{ url_for('static', filename="vendor/toastr/toastr.min.css") }}  rel="stylesheet">
    
</head>
<body>
    <div class="wrapper">
        <div class="auth-content">
            <div class="card">
                <div class="card-body text-center">
                <h1>Flask Notes</h1>
                    <form action="/login" method="POST">
                        <div class="form-group">
                            <input type="text" class="form-control" name="username" placeholder="Username" required>
                        </div>
                        <div class="form-group">
                            <input type="password" class="form-control" name="password" placeholder="Password" required>
                        </div>
                        <button class="btn btn-primary shadow-2 mb-4">Login</button>
                        <br>
                        {% if err %}
                        <span style="color:red">Error: {{err}}</span>
                        {% endif %}

                        {% if msg == "New Version is Available" %}
                            <span style="color:darkorange; font-weight:bold">{{msg}}!</a></span><br>
                            <span style="color:orange"><a href="https://github.com/PaytmLabs/nerve">Download</a></span>
                        {% endif %}
                        <br>
                    </form>
                </div>
            </div>
        </div>
    </div>
    
    <script src={{ url_for('static', filename="vendor/jquery3/jquery-3.4.1.min.js") }}></script>
    <script src={{ url_for('static', filename="vendor/bootstrap4/js/bootstrap.bundle.min.js") }}></script>
    <script src={{ url_for('static', filename="vendor/bootstrap4/js/bootstrap.min.js") }}></script>
    <script src={{ url_for('static', filename="vendor/toastr/toastr.min.js") }}></script>
    <script src={{ url_for('static', filename="js/script.js") }}></script>

    {% with messages = get_flashed_messages(with_categories=true) %}
     {% if messages %}
        <script>
        {% for category, message in messages %}
        toastr.{{category}}("{{ message }}");
        {% endfor %}
        </script>
     {% endif %}
    {% endwith %}
</body>
</html>